// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGrg7z3k-cbEIZ_14OYGqK5-mteTmZOig',
    appId: '1:591910394627:web:f2a654c539d72350866736',
    messagingSenderId: '591910394627',
    projectId: 'lablink-53a91',
    authDomain: 'lablink-53a91.firebaseapp.com',
    storageBucket: 'lablink-53a91.firebasestorage.app',
    measurementId: 'G-0MEXCE31PX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOW-Vfu8X-d7y8vbUyNoHF-ivRAWBvi7U',
    appId: '1:591910394627:ios:6a66507b8b3bb952866736',
    messagingSenderId: '591910394627',
    projectId: 'lablink-53a91',
    storageBucket: 'lablink-53a91.firebasestorage.app',
    androidClientId: '591910394627-n133mpqkghqa24obt329gjr5q1785dsg.apps.googleusercontent.com',
    iosClientId: '591910394627-jnq27r0dnetasdi4b786r719dd88kv44.apps.googleusercontent.com',
    iosBundleId: 'com.lab.lablink',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOW-Vfu8X-d7y8vbUyNoHF-ivRAWBvi7U',
    appId: '1:591910394627:ios:6a66507b8b3bb952866736',
    messagingSenderId: '591910394627',
    projectId: 'lablink-53a91',
    storageBucket: 'lablink-53a91.firebasestorage.app',
    androidClientId: '591910394627-n133mpqkghqa24obt329gjr5q1785dsg.apps.googleusercontent.com',
    iosClientId: '591910394627-jnq27r0dnetasdi4b786r719dd88kv44.apps.googleusercontent.com',
    iosBundleId: 'com.lab.lablink',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGAWShnlPR5OGjnYDJoHiXE3kZeeg1fYo',
    appId: '1:591910394627:android:e75f775080c01bb0866736',
    messagingSenderId: '591910394627',
    projectId: 'lablink-53a91',
    storageBucket: 'lablink-53a91.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGrg7z3k-cbEIZ_14OYGqK5-mteTmZOig',
    appId: '1:591910394627:web:94af25c4a5f67db9866736',
    messagingSenderId: '591910394627',
    projectId: 'lablink-53a91',
    authDomain: 'lablink-53a91.firebaseapp.com',
    storageBucket: 'lablink-53a91.firebasestorage.app',
    measurementId: 'G-7LXY2MFW4B',
  );

}